// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RegistryLookup.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RegistryLookup.Client.Registry.Availability
{
    /// <summary>
    /// Builds and executes requests for operations under \registry\availability
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AvailabilityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RegistryLookup.Client.Registry.Availability.AvailabilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AvailabilityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/registry/availability?registryHost={registryHost}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RegistryLookup.Client.Registry.Availability.AvailabilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AvailabilityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/registry/availability?registryHost={registryHost}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::RegistryLookup.Client.Models.RegistryResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RegistryLookup.Client.Models.RegistryResponse?> GetAsync(Action<RequestConfiguration<global::RegistryLookup.Client.Registry.Availability.AvailabilityRequestBuilder.AvailabilityRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RegistryLookup.Client.Models.RegistryResponse> GetAsync(Action<RequestConfiguration<global::RegistryLookup.Client.Registry.Availability.AvailabilityRequestBuilder.AvailabilityRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::RegistryLookup.Client.Models.RegistryResponse>(requestInfo, global::RegistryLookup.Client.Models.RegistryResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RegistryLookup.Client.Registry.Availability.AvailabilityRequestBuilder.AvailabilityRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RegistryLookup.Client.Registry.Availability.AvailabilityRequestBuilder.AvailabilityRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RegistryLookup.Client.Registry.Availability.AvailabilityRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RegistryLookup.Client.Registry.Availability.AvailabilityRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RegistryLookup.Client.Registry.Availability.AvailabilityRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class AvailabilityRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("registryHost")]
            public string? RegistryHost { get; set; }
#nullable restore
#else
            [QueryParameter("registryHost")]
            public string RegistryHost { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AvailabilityRequestBuilderGetRequestConfiguration : RequestConfiguration<global::RegistryLookup.Client.Registry.Availability.AvailabilityRequestBuilder.AvailabilityRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
