// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RegistryLookup.Client.Registry.Proxy;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RegistryLookup.Client.Registry
{
    /// <summary>
    /// Builds and executes requests for operations under \registry
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RegistryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The proxy property</summary>
        public global::RegistryLookup.Client.Registry.Proxy.ProxyRequestBuilder Proxy
        {
            get => new global::RegistryLookup.Client.Registry.Proxy.ProxyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RegistryLookup.Client.Registry.RegistryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegistryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/registry", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RegistryLookup.Client.Registry.RegistryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegistryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/registry", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
