name: Pull Request

on:
 pull_request:
  branches: [ "main" ]

env:
 DOTNET_VERSION: "9.0.x"
 FRONTEND_APPSETTINGS_FILE: "./source/RegistryLookup.Frontend/wwwroot/appsettings.json"
 BACKEND_APPSETTINGS_FILE: "./source/RegistryLookup.Backend/appsettings.json"

jobs:
 
 pull-request-check:
  runs-on: ubuntu-latest
  
  steps:
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Setup .NET
     uses: actions/setup-dotnet@v4
     with:
      dotnet-version: ${{ env.DOTNET_VERSION }}

   - name: Restore dependencies
     run: |
      dotnet restore

   - name: Build
     run: |
      dotnet build --configuration Release --no-restore

   - name: Install Playwright
     shell: pwsh
     run: |
      ./source/RegistryLookup.Tests.System/bin/Release/net9.0/playwright.ps1 install

   - name: Test
     run: |
      dotnet test --configuration Release

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Build Docker Image
     run: |
      docker build \
        --file ./Dockerfile \
        --build-arg FRONTEND_APPSETTINGS_FILE=${{ env.FRONTEND_APPSETTINGS_FILE }} \
        --build-arg BACKEND_APPSETTINGS_FILE=${{ env.BACKEND_APPSETTINGS_FILE }} \
        --tag test-image .